name: patches-client

executables:
  patches-client:
    main: Main.hs
    source-dirs:
      - ./.
      - ../src
    dependencies:
      - base
      - transformers
      - http-client
      - patches-vector
      - vector
      - string-conversions
      - aeson
      - servant >= 0.5
      - servant-client >= 0.5
      - containers
      - react-flux
      - ghcjs-base
      - deepseq
