name: patches-client

executables:
  patches-client:
    main: Main.hs
    source-dirs:
      - ./.
      - ../src
    dependencies:
      - base
      - reflex-dom
      - patches-vector
      - vector
      - string-conversions
      - aeson
      - servant >= 0.5
      - containers
