name: patches-client

executables:
  patches-client:
    main: Main.hs
    source-dirs:
      - ./.
      - ../src
    dependencies:
      - base
      - transformers
      - http-client
      - string-conversions
      - crdt-tree-vector
      - text
      - unordered-containers
      - aeson
      - servant >= 0.5
      - servant-client >= 0.5
      - containers
      - react-flux
      - ghcjs-base
      - ghcjs-prim
      - random
      - safe
      - deepseq
