flags: {}

packages:
  - location: ./.
  - location: /home/shahn/src/servant
    subdirs:
      - servant
      - servant-client
    extra-dep: true
  - location: /home/shahn/src/crdt-tree-vector
    extra-dep: true

resolver: lts-3.10

compiler: ghcjs-0.2.0.20151029_ghc-7.10.2
compiler-check: match-exact
setup-info:
 ghcjs:
  source:
   ghcjs-0.2.0.20151029_ghc-7.10.2:
    url: "https://github.com/nrolland/ghcjs/releases/download/v0.2.0.20151029/ghcjs-0.2.0.20151029.tar.gz"

extra-deps:
  - edit-distance-vector-1.0.0.2
  - http-api-data-0.1.1.1
  - react-flux-1.0.2
  - patches-vector-0.1.5.0
