flags: {}

packages:
- location: ./.
- location:
    git: https://github.com/ryantrinkle/reflex
    commit: 784f9f79396ae713a03fc4d81f8a67b75d6ade1c # need a few package bumps not present in hackage release yet
  extra-dep: true
- location:
    git: https://github.com/ryantrinkle/reflex-dom
    commit: a60ae687cdc284a8eb3776fc95aa2adefc51e7ec # hamishmack-master (improved-base compatible)
  extra-dep: true
- location:
    git: https://github.com/soenkehahn/generics-eot
    commit: 11cc9be9defa2e450b6189951abd0e15a79e621a
  extra-dep: true
- location:
    git: https://github.com/haskell-servant/servant
    commit: fdd1829c8fc43cdc92b28b6ef2854452ceb5e16c
  subdirs:
    - servant
  extra-dep: true

resolver: lts-3.10

compiler: ghcjs-0.2.0.20151001_ghc-7.10.2
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.20151001_ghc-7.10.2:
        url: "https://github.com/fizruk/ghcjs/releases/download/v0.2.0.20151001/ghcjs-0.2.0.20151001.tar.gz"

extra-deps:
  - ref-tf-0.4
  - these-0.6.1.0
  - ghcjs-dom-0.2.2.0 # improved-base compatible with (2015-10-01 ghcjs)
  - patches-vector-0.1.4.4
  - edit-distance-vector-1.0.0.2
  - http-api-data-0.1.1.1
