ghc-options: -Wall

executables:
  patches:
    main: Main.hs
    source-dirs:
      - src
    dependencies:
      - base
      - wai
      - wai-shake
      - warp
      - logging-facade
      - servant >= 0.5
      - servant-server >= 0.5
      - getopt-generics
      - http-types
