executables:
  patches:
    main: Main.hs
    source-dirs:
      - src
    dependencies:
      - base
      - wai
      - wai-ghcjs
      - warp
      - logging-facade
      - servant >= 0.5
      - servant-server >= 0.5
      - getopt-generics
      - crdt-tree-vector
      - aeson >= 0.10
      - containers
      - unordered-containers
      - string-conversions
      - text
      - safe
      - either
      - transformers
      - deepseq
