resolver: nightly-2015-11-11
packages:
  - '.'
  - location:
      git: https://github.com/soenkehahn/wai-shake
      commit: 57947ab4a61e7d4790e2168bc5c9c16b47b5ca59
    extra-dep: true
extra-deps: []
flags: {}
extra-package-dbs: []
